# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47eb030928ae65b620b4163076c27598bbaf3ec9deb1737c9cbab3a3003ade35a91cf6800fe700ffbff5d09b80beabef9e542515586cf2760587f1ce3028536f

test:
  secret_key_base: 3726bad158ee3cb0865836dabd5996ce1134a4629b5779555b966974e4b1905b830ce4f46b2ece8a49b32743af805755a060cf81ab20bffeddb716da4c3ecda6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
